In [ ]:
pd.set_option('display.max_rows', None)

In [31]:
import pandas as pd
from datetime import datetime
 
df_data1 = pd.read_table('./Task/muse_rawdata/session 5.csv',sep=',') # 여기 들어가는 데이터는 muse에서 바로 뽑은 데이터
df_data1 = df_data1.drop('Elements', axis=1) # Elements 컬럼 drop
df_data1= df_data1.dropna(axis=0) # 결측치 있는 행 drop
df_data1.info()
df_data1.isnull().sum() # 결측치 없는거 확인하기

<class 'pandas.core.frame.DataFrame'>
Int64Index: 67260 entries, 0 to 67309
Data columns (total 38 columns):
TimeStamp          67260 non-null object
Delta_TP9          67260 non-null float64
Delta_AF7          67260 non-null float64
Delta_AF8          67260 non-null float64
Delta_TP10         67260 non-null float64
Theta_TP9          67260 non-null float64
Theta_AF7          67260 non-null float64
Theta_AF8          67260 non-null float64
Theta_TP10         67260 non-null float64
Alpha_TP9          67260 non-null float64
Alpha_AF7          67260 non-null float64
Alpha_AF8          67260 non-null float64
Alpha_TP10         67260 non-null float64
Beta_TP9           67260 non-null float64
Beta_AF7           67260 non-null float64
Beta_AF8           67260 non-null float64
Beta_TP10          67260 non-null float64
Gamma_TP9          67260 non-null float64
Gamma_AF7          67260 non-null float64
Gamma_AF8          67260 non-null float64
Gamma_TP10         67260 non-null float64
RAW_TP9            67260 non-null float64
RAW_AF7            67260 non-null float64
RAW_AF8            67260 non-null float64
RAW_TP10           67260 non-null float64
AUX_RIGHT          67260 non-null float64
Accelerometer_X    67260 non-null float64
Accelerometer_Y    67260 non-null float64
Accelerometer_Z    67260 non-null float64
Gyro_X             67260 non-null float64
Gyro_Y             67260 non-null float64
Gyro_Z             67260 non-null float64
HeadBandOn         67260 non-null float64
HSI_TP9            67260 non-null float64
HSI_AF7            67260 non-null float64
HSI_AF8            67260 non-null float64
HSI_TP10           67260 non-null float64
Battery            67260 non-null float64
dtypes: float64(37), object(1)
memory usage: 20.0+ MB

TimeStamp          0
Delta_TP9          0
Delta_AF7          0
Delta_AF8          0
Delta_TP10         0
Theta_TP9          0
Theta_AF7          0
Theta_AF8          0
Theta_TP10         0
Alpha_TP9          0
Alpha_AF7          0
Alpha_AF8          0
Alpha_TP10         0
Beta_TP9           0
Beta_AF7           0
Beta_AF8           0
Beta_TP10          0
Gamma_TP9          0
Gamma_AF7          0
Gamma_AF8          0
Gamma_TP10         0
RAW_TP9            0
RAW_AF7            0
RAW_AF8            0
RAW_TP10           0
AUX_RIGHT          0
Accelerometer_X    0
Accelerometer_Y    0
Accelerometer_Z    0
Gyro_X             0
Gyro_Y             0
Gyro_Z             0
HeadBandOn         0
HSI_TP9            0
HSI_AF7            0
HSI_AF8            0
HSI_TP10           0
Battery            0
dtype: int64

In [32]:
# 필요한 열 골라서 dataframe으로 만들기.
data = df_data1[df_data1.columns[[0,3,7,11,15,19]]] #AF8 채널 이용

In [33]:
data['stimulus'] = 0

<ipython-input-33-29a890b34423>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['stimulus'] = 0

In [34]:
data

,TimeStamp,Delta_AF8,Theta_AF8,Alpha_AF8,Beta_AF8,Gamma_AF8,stimulus
0,2022-07-22 16:47:05.270,0.653585,0.779724,0.756711,0.682772,0.091385,0
1,2022-07-22 16:47:05.271,0.653585,0.779724,0.756711,0.682772,0.091385,0
2,2022-07-22 16:47:05.271,0.653585,0.779724,0.756711,0.682772,0.091385,0
3,2022-07-22 16:47:05.271,0.653585,0.779724,0.756711,0.682772,0.091385,0
4,2022-07-22 16:47:05.272,0.653585,0.779724,0.756711,0.682772,0.091385,0
...,...,...,...,...,...,...,...
67305,2022-07-22 16:51:27.944,0.756288,0.337619,0.567640,0.647005,0.448585,0
67306,2022-07-22 16:51:27.945,0.756288,0.337619,0.567640,0.647005,0.448585,0
67307,2022-07-22 16:51:27.945,0.756288,0.337619,0.567640,0.647005,0.448585,0
67308,2022-07-22 16:51:27.945,0.756288,0.337619,0.567640,0.647005,0.448585,0
67309,2022-07-22 16:51:27.945,0.756288,0.337619,0.567640,0.647005,0.448585,0

In [35]:
data.to_excel("./clean_dataset/session_5_clean.xlsx") # clean data로 저장.

In [43]:
type(data['TimeStamp'][0])

str

In [71]:
time_1 = datetime.strptime(data['TimeStamp'][0], "%Y-%m-%d %H:%M:%S.%f")
time_2 = datetime.strptime(data['TimeStamp'][11110], "%Y-%m-%d %H:%M:%S.%f")
time_0 = datetime.strptime('0:00:00.000000', "%H:%M:%S.%f")
time_interval = time_2 - time_1
print(time_interval)
time_interval= datetime.strptime(str(time_interval), "%H:%M:%S.%f")

if time_interval > time_0:
    print('f')

0:00:43.289000
f

In [54]:
import pandas as pd
from datetime import datetime
 
stimulus = pd.read_table('./dataset/trial2.txt',sep='\n') 
stimulus.columns = ["time"]
stimulus['mark'] = 0

In [55]:
stimulus

                                time  mark
0    2022-07-05 14:03:27.858215 rest     0
1     2022-07-05 14:03:57.865057 red     0
2    2022-07-05 14:03:58.865122 rest     0
3     2022-07-05 14:04:03.854548 red     0
4    2022-07-05 14:04:04.862093 rest     0
5     2022-07-05 14:04:09.866220 red     0
6    2022-07-05 14:04:10.866275 rest     0
7     2022-07-05 14:04:15.863844 red     0
8    2022-07-05 14:04:16.854636 rest     0
9     2022-07-05 14:04:21.859523 red     0
10   2022-07-05 14:04:22.861944 rest     0
11  2022-07-05 14:04:27.854496 green     0
12   2022-07-05 14:04:28.853615 rest     0
13  2022-07-05 14:04:33.863399 green     0
14   2022-07-05 14:04:34.863452 rest     0
15  2022-07-05 14:04:39.858988 green     0
16   2022-07-05 14:04:40.859032 rest     0
17  2022-07-05 14:04:45.867395 green     0
18   2022-07-05 14:04:46.856075 rest     0
19  2022-07-05 14:04:51.862555 green     0
20   2022-07-05 14:04:52.862611 rest     0
21   2022-07-05 14:04:57.856540 blue     0
22   2022-07-05 14:04:58.858615 rest     0
23   2022-07-05 14:05:03.853928 blue     0
24   2022-07-05 14:05:04.854002 rest     0
25   2022-07-05 14:05:09.865381 blue     0
26   2022-07-05 14:05:10.867771 rest     0
27   2022-07-05 14:05:15.865395 blue     0
28   2022-07-05 14:05:16.865975 rest     0
29   2022-07-05 14:05:21.857369 blue     0
30   2022-07-05 14:05:22.862104 rest     0
31   2022-07-05 14:05:27.854177  end     0

In [56]:
for i in range(len(stimulus)):
    stimulus['mark'][i] = stimulus['time'][i][27:]    
    stimulus['time'][i] = stimulus['time'][i][:26]

C:\Users\hhz20\AppData\Local\Temp/ipykernel_4276/370938349.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stimulus['mark'][i] = stimulus['time'][i][27:]
C:\Users\hhz20\anaconda3\lib\site-packages\pandas\core\indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

In [57]:
stimulus

                          time   mark
0   2022-07-05 14:03:27.858215   rest
1   2022-07-05 14:03:57.865057    red
2   2022-07-05 14:03:58.865122   rest
3   2022-07-05 14:04:03.854548    red
4   2022-07-05 14:04:04.862093   rest
5   2022-07-05 14:04:09.866220    red
6   2022-07-05 14:04:10.866275   rest
7   2022-07-05 14:04:15.863844    red
8   2022-07-05 14:04:16.854636   rest
9   2022-07-05 14:04:21.859523    red
10  2022-07-05 14:04:22.861944   rest
11  2022-07-05 14:04:27.854496  green
12  2022-07-05 14:04:28.853615   rest
13  2022-07-05 14:04:33.863399  green
14  2022-07-05 14:04:34.863452   rest
15  2022-07-05 14:04:39.858988  green
16  2022-07-05 14:04:40.859032   rest
17  2022-07-05 14:04:45.867395  green
18  2022-07-05 14:04:46.856075   rest
19  2022-07-05 14:04:51.862555  green
20  2022-07-05 14:04:52.862611   rest
21  2022-07-05 14:04:57.856540   blue
22  2022-07-05 14:04:58.858615   rest
23  2022-07-05 14:05:03.853928   blue
24  2022-07-05 14:05:04.854002   rest
25  2022-07-05 14:05:09.865381   blue
26  2022-07-05 14:05:10.867771   rest
27  2022-07-05 14:05:15.865395   blue
28  2022-07-05 14:05:16.865975   rest
29  2022-07-05 14:05:21.857369   blue
30  2022-07-05 14:05:22.862104   rest
31  2022-07-05 14:05:27.854177    end

In [60]:
stimulus['time'][[stimulus['mark'][i] == 'red'].index]

IndexError: Boolean index has wrong length: 1 instead of 32

In [64]:
if data['TimeStamp'][i] - stimulus['time'] > 0 :
    data['stimulus'][i] = 1

,TimeStamp,Delta_AF7,Theta_AF7,Alpha_AF7,Beta_AF7,Gamma_AF7,stimulus
0,2022-07-05 14:03:30.972,0.787475,0.355094,0.662357,1.185562,0.850897,0
1,2022-07-05 14:03:30.973,0.787475,0.355094,0.662357,1.185562,0.850897,0
2,2022-07-05 14:03:30.973,0.787475,0.355094,0.662357,1.185562,0.850897,0
3,2022-07-05 14:03:30.974,0.787475,0.355094,0.662357,1.185562,0.850897,0
4,2022-07-05 14:03:30.974,0.787475,0.355094,0.662357,1.185562,0.850897,0
...,...,...,...,...,...,...,...
31286,2022-07-05 14:05:33.036,0.590314,0.417819,0.668900,0.957642,0.858311,0
31287,2022-07-05 14:05:33.036,0.590314,0.417819,0.668900,0.957642,0.858311,0
31288,2022-07-05 14:05:33.036,0.590314,0.417819,0.668900,0.957642,0.858311,0
31289,2022-07-05 14:05:33.037,0.590314,0.417819,0.668900,0.957642,0.858311,0
31290,2022-07-05 14:05:33.037,0.590314,0.417819,0.668900,0.957642,0.858311,0

In [72]:
time_0 = datetime.strptime('0:00:00.000000', "%H:%M:%S.%f") # 0초 만들기

for i in range(len(stimulus)) :
    for k in range(len(data)) :
        time_data = datetime.strptime(data['TimeStamp'][k], "%Y-%m-%d %H:%M:%S.%f")
        time_stimulus = datetime.strptime(stimulus['time'][i], "%Y-%m-%d %H:%M:%S.%f")
        time_interval= datetime.strptime(str(time_data - time_stimulus), "%H:%M:%S.%f")
        
        if time_interval > time_0 :
            data['stimulus'][i] = 1
            print(k)
            break

0

C:\Users\hhz20\AppData\Local\Temp/ipykernel_4276/1644359434.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['stimulus'][i] = 1

ValueError: time data '-1 day, 23:59:33.106943' does not match format '%H:%M:%S.%f'

In [74]:
data.to_excel('data.xlsx')