In [1]:
import pandas as pd
from datetime import datetime

data = pd.read_excel('./clean_dataset/session_1_clean.xlsx') # stimulus 시점 표시된 clean data 가져오기.

In [2]:
data

,Unnamed: 0,TimeStamp,Delta_AF8,Theta_AF8,Alpha_AF8,Beta_AF8,Gamma_AF8,stimulus
0,0,2022-07-17 21:58:53.395,0.949376,0.573613,0.547831,0.596918,0.446937,0
1,1,2022-07-17 21:58:53.396,0.949376,0.573613,0.547831,0.596918,0.446937,0
2,2,2022-07-17 21:58:53.397,0.949376,0.573613,0.547831,0.596918,0.446937,0
3,3,2022-07-17 21:58:53.397,0.949376,0.573613,0.547831,0.596918,0.446937,0
4,4,2022-07-17 21:58:53.398,0.949376,0.573613,0.547831,0.596918,0.446937,0
...,...,...,...,...,...,...,...,...
66595,66619,2022-07-17 22:03:13.438,0.654283,0.152747,0.076497,0.381576,0.357279,0
66596,66620,2022-07-17 22:03:13.439,0.654283,0.152747,0.076497,0.381576,0.357279,0
66597,66621,2022-07-17 22:03:13.439,0.654283,0.152747,0.076497,0.381576,0.357279,0
66598,66622,2022-07-17 22:03:13.439,0.654283,0.152747,0.076497,0.381576,0.357279,0
66599,66623,2022-07-17 22:03:13.440,0.654283,0.152747,0.076497,0.381576,0.357279,0

In [3]:
data = data.drop('Unnamed: 0', axis = 1)

In [5]:
data['stimulus'].unique()

array([0, 1], dtype=int64)

In [6]:
data.head()

,TimeStamp,Delta_AF8,Theta_AF8,Alpha_AF8,Beta_AF8,Gamma_AF8,stimulus
0,2022-07-17 21:58:53.395,0.949376,0.573613,0.547831,0.596918,0.446937,0
1,2022-07-17 21:58:53.396,0.949376,0.573613,0.547831,0.596918,0.446937,0
2,2022-07-17 21:58:53.397,0.949376,0.573613,0.547831,0.596918,0.446937,0
3,2022-07-17 21:58:53.397,0.949376,0.573613,0.547831,0.596918,0.446937,0
4,2022-07-17 21:58:53.398,0.949376,0.573613,0.547831,0.596918,0.446937,0

In [10]:
point = []
point.append(0)
for i in range(len(data)) :
    if data['stimulus'][i] == 1:
        point.append(i)
point.append(len(data))

In [17]:
data['temp'] = 0

In [52]:
datetime.strptime(data['TimeStamp'][point[0]], "%Y-%m-%d %H:%M:%S.%f")

datetime.datetime(2022, 7, 5, 14, 3, 57, 862000)

In [15]:
# time_s = datetime.timedelta(days=14)
time_s = datetime.strptime('0:00:01.100000', "%H:%M:%S.%f")  - datetime.strptime('0:00:00.100000', "%H:%M:%S.%f") 
time_e = datetime.strptime('0:00:01.000000', "%H:%M:%S.%f")  - datetime.strptime('0:00:00.500000', "%H:%M:%S.%f") 
# time_delta로 맞춰줘야해서 
print(time_s, time_e)

0:00:01 0:00:00.500000

In [26]:
point = []
point.append(0)
for i in range(len(data)) :
    if data['stimulus_time'][i] == 1:
        point.append(i)
point.append(len(data))

In [18]:
data['temp'] = 0
start_idx = 0
end_idx = 0
# time_s = datetime.timedelta(days=14)
time_s = datetime.strptime('0:00:01.100000', "%H:%M:%S.%f")  - datetime.strptime('0:00:00.100000', "%H:%M:%S.%f") 
time_e = datetime.strptime('0:00:01.000000', "%H:%M:%S.%f")  - datetime.strptime('0:00:00.500000', "%H:%M:%S.%f") 
# time_delta로 맞춰줘야해서 
# print(time_s, time_e)

# time_s = datetime.strptime('0:00:01.000000', "%H:%M:%S.%f") # 200ms 만들기
# time_e = datetime.strptime('0:00:00.500000', "%H:%M:%S.%f") # 200ms 만들기

for j in range(0, len(point)-1) :
    for i in range(point[j-1], point[j]) : # stimulus time부터 앞으로 1.0~0.5s에 1 표시한거 즉, 자극 이전 레퍼런스 eeg
        time_stimulus = datetime.strptime(data['TimeStamp'][point[j]], "%Y-%m-%d %H:%M:%S.%f") # stimulus 가 1인 시간.
        time_data = datetime.strptime(data['TimeStamp'][i], "%Y-%m-%d %H:%M:%S.%f")
        time_interval = time_stimulus - time_data
        if time_interval > time_e and time_interval < time_s :
            data['temp'][i] = str(j) + 'ref'
        
    for i in range(point[j], point[j+1]) : # stimulus time부터 뒤로 0.5~1.0s에 2 표시한거 즉, 자극 이후 변화한 eeg
        time_stimulus = datetime.strptime(data['TimeStamp'][point[j]], "%Y-%m-%d %H:%M:%S.%f") # stimulus 가 1인 시간.
        time_data = datetime.strptime(data['TimeStamp'][i], "%Y-%m-%d %H:%M:%S.%f")
        time_interval = -(time_stimulus - time_data)
        if time_interval > time_e and time_interval < time_s :
            data['temp'][i] = str(j) + 'after'

C:\Users\hhz20\AppData\Local\Temp/ipykernel_420/2250256414.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['temp'][i] = str(j) + 'after'
C:\Users\hhz20\anaconda3\lib\site-packages\pandas\core\indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

In [19]:
data.to_excel("./clean_dataset/clean_stimulus/session_1_clean_stimulus.xlsx")

In [ ]:
# temp ='1ref' 인거끼리 평균. temp ='1after' 인거끼리 평균. 
# 그렇게 해서 비율 구해보면 됨. 
# 그리고 뇌파 새로 측정해서 해보기  ㅇ
# 예를 들어 after를 1초를 뽑아서 200ms씩 plot 을 해본다던가
# 비율은 기본적으로 계산해서 표로 정리하고. (자극 시점 1초 제외하고 앞뒤 0.5 초 간의 증감 비율 등)
# 히트맵은 어떻게 하는건지 생각좀 해보기.

In [23]:
import pandas as pd
from datetime import datetime

data = pd.read_excel('./clean_dataset/clean_stimulus/session_1_clean_stimulus.xlsx') # stimulus 시점 표시된 clean data 가져오기.

In [24]:
for i in range(0, point[1]):
    if data['temp'][i] == '1ref' :
        print(i)

7308
7309
7310
7311
7312
7313
7314
7315
7316
7317
7318
7319
7320
7321
7322
7323
7324
7325
7326
7327
7328
7329
7330
7331
7332
7333
7334
7335
7336
7337
7338
7339
7340
7341
7342
7343
7344
7345
7346
7347
7348
7349
7350
7351
7352
7353
7354
7355
7356
7357
7358
7359
7360
7361
7362
7363
7364
7365
7366
7367
7368
7369
7370
7371
7372
7373
7374
7375
7376
7377
7378
7379
7380
7381
7382
7383
7384
7385
7386
7387
7388
7389
7390
7391
7392
7393
7394
7395
7396
7397
7398
7399
7400
7401
7402
7403
7404
7405
7406
7407
7408
7409
7410
7411
7412
7413
7414
7415
7416
7417
7418
7419
7420
7421
7422
7423
7424
7425
7426
7427
7428
7429
7430
7431
7432
7433
7434
7435
7436
7437
7438
7439

In [44]:
## 데이터 추출 연습용
data[data['temp'] == '1ref']['Delta_AF8'].mean()

-0.2059544947727275

In [53]:
# 빈 데이터프레임 생성.
df_ratio = pd.DataFrame(columns=['ratio_delta','ratio_theta','ratio_alpha','ratio_beta','ratio_gamma'])

In [59]:
# 빈 데이터프레임 생성.
df_ratio = pd.DataFrame(columns=['ratio_delta','ratio_theta','ratio_alpha','ratio_beta','ratio_gamma'])
for i in range(1, 16):
    ref_delta = data[data['temp'] == str(i)+'ref']['Delta_AF8'].mean()
    after_delta = data[data['temp'] == str(i)+'after']['Delta_AF8'].mean()
    ratio_delta = (after_delta-ref_delta)/ref_delta
    if ref_delta < 0 : 
        ratio_delta = -(ratio_delta)
    
    ref_theta = data[data['temp'] == str(i)+'ref']['Theta_AF8'].mean()
    after_theta = data[data['temp'] == str(i)+'after']['Theta_AF8'].mean()
    ratio_theta = (after_theta-ref_theta)/ref_theta
    if ref_theta < 0 : 
        ratio_theta = -(ratio_theta)
    
    ref_alpha = data[data['temp'] == str(i)+'ref']['Alpha_AF8'].mean()
    after_alpha = data[data['temp'] == str(i)+'after']['Alpha_AF8'].mean()
    ratio_alpha = (after_alpha-ref_alpha)/ref_alpha
    if ref_alpha < 0 : 
        ratio_alpha = -(ratio_alpha)
    
    ref_beta = data[data['temp'] == str(i)+'ref']['Beta_AF8'].mean()
    after_beta = data[data['temp'] == str(i)+'after']['Beta_AF8'].mean()
    ratio_beta = (after_beta-ref_beta)/ref_beta
    if ref_beta < 0 : 
        ratio_beta = -(ratio_beta)
    
    ref_gamma = data[data['temp'] == str(i)+'ref']['Gamma_AF8'].mean()
    after_gamma = data[data['temp'] == str(i)+'after']['Gamma_AF8'].mean()
    ratio_gamma = (after_gamma-ref_gamma)/ref_gamma
    if ref_gamma < 0 : 
        ratio_gamma = -(ratio_gamma)
    
    df_ratio.loc[i]=[ratio_delta,ratio_theta,ratio_alpha,ratio_beta, ratio_gamma]

In [60]:
df_ratio

    ratio_delta  ratio_theta  ratio_alpha  ratio_beta  ratio_gamma
1      0.436191    -0.937787    -0.247170   -0.289132    -0.328348
2     -0.641469    -1.238356    -0.529864    0.538040    -0.098814
3     -1.308863     0.989612     0.136370   -0.443294    -0.945219
4     -0.298352    -1.404642     0.515931   -0.291847     1.464473
5      1.410717     0.592085    -0.266043   -0.355954     0.132531
6     -5.255050    -0.638485    -0.219851   -0.154670    -0.520992
7      6.900116    -0.060484    -0.634612   -0.147606    -0.276178
8     -1.099028     0.822039     0.974372    0.378420     0.710410
9     -1.253142     1.118494    -0.274762   -0.038394     0.337698
10     1.751215     1.837039    -0.653283   -0.328165    -0.525722
11    -0.058284    -0.287923     0.309045   -0.117484    -0.013880
12    -0.489619    -0.853259     0.046695    0.105818    -0.043329
13     1.398087     0.942695     1.172327   -0.313151    -0.222022
14    -2.574244     1.085365    -0.141340    0.423822     0.183207
15     0.045276    -0.746368    -0.352230   -0.110916    -0.188750

In [55]:
df_ratio

    ratio_delta  ratio_theta  ratio_alpha  ratio_beta  ratio_gamma
1     -0.436191    -0.937787    -0.247170   -0.289132    -0.328348
2     -0.641469    -1.238356    -0.529864    0.538040    -0.098814
3     -1.308863    -0.989612     0.136370   -0.443294    -0.945219
4      0.298352    -1.404642     0.515931   -0.291847     1.464473
5     -1.410717    -0.592085    -0.266043   -0.355954     0.132531
6     -5.255050    -0.638485    -0.219851   -0.154670    -0.520992
7      6.900116    -0.060484    -0.634612   -0.147606    -0.276178
8      1.099028    -0.822039     0.974372    0.378420     0.710410
9      1.253142    -1.118494    -0.274762   -0.038394     0.337698
10     1.751215    -1.837039    -0.653283   -0.328165    -0.525722
11    -0.058284    -0.287923     0.309045   -0.117484    -0.013880
12    -0.489619    -0.853259     0.046695    0.105818    -0.043329
13     1.398087    -0.942695     1.172327   -0.313151    -0.222022
14    -2.574244    -1.085365    -0.141340    0.423822     0.183207
15     0.045276    -0.746368    -0.352230   -0.110916    -0.188750

In [56]:
# 비율 말고 증가값으로 보기
# 빈 데이터프레임 생성.
df_increase = pd.DataFrame(columns=['increase_delta','increase_theta','increase_alpha','increase_beta','ratio_gamma'])

for i in range(1, 16):
    ref_delta = data[data['temp'] == str(i)+'ref']['Delta_AF8'].mean()
    after_delta = data[data['temp'] == str(i)+'after']['Delta_AF8'].mean()
    increase_delta = (after_delta-ref_delta)
    
    ref_theta = data[data['temp'] == str(i)+'ref']['Theta_AF8'].mean()
    after_theta = data[data['temp'] == str(i)+'after']['Theta_AF8'].mean()
    increase_theta = (after_theta-ref_theta)
    
    ref_alpha = data[data['temp'] == str(i)+'ref']['Alpha_AF8'].mean()
    after_alpha = data[data['temp'] == str(i)+'after']['Alpha_AF8'].mean()
    increase_alpha = (after_alpha-ref_alpha)
    
    ref_beta = data[data['temp'] == str(i)+'ref']['Beta_AF8'].mean()
    after_beta = data[data['temp'] == str(i)+'after']['Beta_AF8'].mean()
    increase_beta = (after_beta-ref_beta)
    
    ref_gamma = data[data['temp'] == str(i)+'ref']['Gamma_AF8'].mean()
    after_gamma = data[data['temp'] == str(i)+'after']['Gamma_AF8'].mean()
    increase_gamma = (after_gamma-ref_gamma)
    
    df_increase.loc[i]=[increase_delta,increase_theta,increase_alpha,increase_beta, increase_gamma]

In [57]:
df_increase

    increase_delta  increase_theta  increase_alpha  increase_beta  ratio_gamma
1         0.089836       -0.373626       -0.098954      -0.192930    -0.161312
2        -0.481983       -0.338828       -0.265053       0.190845    -0.023385
3        -0.419692        0.146132        0.040179      -0.237649    -0.159507
4        -0.008820       -0.201081        0.120411      -0.150002     0.131797
5         0.352973        0.050781       -0.120760      -0.189432     0.008909
6        -0.134491       -0.059466       -0.093711      -0.098098    -0.208043
7         0.394835       -0.005258       -0.300302      -0.085004    -0.112048
8        -0.069320        0.163304        0.270719       0.186625     0.179983
9        -0.095815        0.436263       -0.071173      -0.018936     0.061345
10        0.030493        0.206676       -0.291888      -0.190699    -0.084635
11       -0.030524       -0.015111        0.115042      -0.068330    -0.004195
12       -0.271548       -0.209086        0.018962       0.066176    -0.014895
13        0.347358        0.165845        0.205160      -0.169911    -0.033422
14       -0.092534        0.114432       -0.043813       0.137300     0.026578
15        0.020452       -0.123442       -0.176594      -0.060408    -0.044671

In [ ]:
# 빈 데이터프레임 생성.
df_ratio = pd.DataFrame(columns=['ratio_delta','ratio_theta','ratio_alpha','ratio_beta','ratio_gamma','stimulusOrNot'])
# 첫 클릭시점부터 마지막 클릭시점 이후 3초까지 루프 돌면서 증감율 구하기. 0123(클릭)4
for i in range(stimulus_row_num[0]-2, stimulus_row_num[-1]+3):
    stimulusOrNot = 0    
    if i+2 in stimulus_row_num :
        stimulusOrNot = 1
    ref_delta = df1[i:i+2].mean()[0]
    after_delta = df1[i+3:i+5].mean()[0]
    ratio_delta = (after_delta-ref_delta)/ref_delta
    
    ref_theta = df1[i:i+2].mean()[1]
    after_theta = df1[i+3:i+5].mean()[1]
    ratio_theta = (after_theta-ref_theta)/ref_theta
    
    ref_alpha = df1[i:i+2].mean()[2]
    after_alpha = df1[i+3:i+5].mean()[2]
    ratio_alpha = (after_alpha-ref_alpha)/ref_alpha
    
    ref_beta = df1[i:i+2].mean()[3]
    after_beta = df1[i+3:i+5].mean()[3]
    ratio_beta = (after_beta-ref_beta)/ref_beta
    
    ref_gamma = df1[i:i+2].mean()[4]
    after_gamma = df1[i+3:i+5].mean()[4]
    ratio_gamma = (after_gamma-ref_gamma)/ref_gamma
    
    
    df_ratio.loc[i+2]=[ratio_delta,ratio_theta,ratio_alpha,ratio_beta, ratio_gamma, stimulusOrNot]

In [ ]:
time_0 = datetime.strptime('0:00:00.000000', "%H:%M:%S.%f") # 0초 만들기

for i in range(len(stimulus)) :
    for k in range(len(data)) :
        time_data = datetime.strptime(data['TimeStamp'][k], "%Y-%m-%d %H:%M:%S.%f")
        time_stimulus = datetime.strptime(stimulus['time'][i], "%Y-%m-%d %H:%M:%S.%f")
        time_interval= datetime.strptime(str(time_data - time_stimulus), "%H:%M:%S.%f")
        
        if time_interval > time_0 :
            data['stimulus'][i] = 1
            print(k)
            break
        print(k)

In [ ]:
start_idx = 0
end_idx = 0
# time_s = datetime.timedelta(days=14)
time_s = datetime.strptime('0:00:01.100000', "%H:%M:%S.%f")  - datetime.strptime('0:00:00.100000', "%H:%M:%S.%f") 
time_e = datetime.strptime('0:00:01.000000', "%H:%M:%S.%f")  - datetime.strptime('0:00:00.500000', "%H:%M:%S.%f") 
# time_delta로 맞춰줘야해서 
print(time_s, time_e)

# time_s = datetime.strptime('0:00:01.000000', "%H:%M:%S.%f") # 200ms 만들기
# time_e = datetime.strptime('0:00:00.500000', "%H:%M:%S.%f") # 200ms 만들기

for i in range(point[0], point[0]) : # stimulus time부터 앞으로 1.0~0.5s에 1 표시한거 즉, 자극 이전 레퍼런스 eeg
    time_stimulus = datetime.strptime(data['TimeStamp'][point[0]], "%Y-%m-%d %H:%M:%S.%f") # stimulus 가 1인 시간.
    time_data = datetime.strptime(data['TimeStamp'][i], "%Y-%m-%d %H:%M:%S.%f")
#     print(time_stimulus - time_data)
    time_interval = time_stimulus - time_data
#     time_interval= datetime.strptime(str(time_stimulus - time_data), "%H:%M:%S.%f")
    if time_interval > time_e and time_interval < time_s :
#         print('1')
        data['temp'][i] = 1
        
for i in range(point[0], point[1]) : # stimulus time부터 뒤로 0.5~1.0s에 2 표시한거 즉, 자극 이후 변화한 eeg
    time_stimulus = datetime.strptime(data['TimeStamp'][point[0]], "%Y-%m-%d %H:%M:%S.%f") # stimulus 가 1인 시간.
#     time_data = datetime.strptime(data['TimeStamp'][i], "%Y-%m-%d %H:%M:%S.%f")
    print(time_stimulus - time_data)
    time_interval = -(time_stimulus - time_data)
#     time_interval= datetime.strptime(str(time_stimulus - time_data), "%H:%M:%S.%f")
    if time_interval > time_e and time_interval < time_s :
#         print('2')
        data['temp'][i] = 2
        
# for j in range(0, len(point)) :
#     for i in range(0, point[i]) :
#     time_stimulus = datetime.strptime(data['TimeStamp'][point[j]], "%Y-%m-%d %H:%M:%S.%f") # stimulus 가 1인 시간.
#     time_data = datetime.strptime(data['TimeStamp'][i], "%Y-%m-%d %H:%M:%S.%f")
#     print(time_stimulus - time_data)
#     time_interval = time_stimulus - time_data
# #     time_interval= datetime.strptime(str(time_stimulus - time_data), "%H:%M:%S.%f")
#     if time_interval > time_e and time_interval < time_s :
#         print('1')
#         data['temp'][i] = 1